compressionLevel: 0

defaultSemverRangePrefix: ''

enableScripts: false

enableTelemetry: false

injectEnvironmentFiles:
  - .env?
  - .env.yarn?
  - .env.development?

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 120

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.12.0.cjs
