compressionLevel: 0

enableTelemetry: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.6.0.cjs
